version: '3.7'

services:
  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - "6379:6379"
  bot:
    build: .
    command: "python3 -m bot"
    env_file:
      - ./.env
    restart: always
    ports:
      - "7771:7771"
    # working_dir: "/root/bots/aiogram_template"
    stop_signal: SIGINT
  worker:
    build: .
    command: "python3 -m captcha"
    restart: on-failure
    # working_dir: "/root/bots/aiogram_template"
    stop_signal: SIGINT