version: '3.7'

services:
  redis:
    image: redis:alpine
    command:
      - redis-server
    env_file:
      - ./.env
    restart: on-failure
    # ports:
    #   - "6379:6379"
  bot:
    build: .
    command: "python -m bot"
    env_file:
      - ./.env
    restart: always
    ports:
      -"7771:7771"
  worker:
    build: .
    command: "python -m captcha"
    restart: on-failure