name: Telegram Bot CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Trying to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /root/bots/aiogram_template
            git checkout .
            git pull
            pip3 install -r requirements.txt
            pybabel compile -d bot/locales -D messages
            systemctl restart tg_bot
